code-llm:
  # ## 01.ai
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "yi-lightning"

  # deepseek v3
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "deepseek-v3"

  # # deepseek v2.5
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "deepseek-v2.5"

  # ## Qwen/Qwen2.5
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "Qwen/Qwen2.5-72B-Instruct-128K"

  ## Argo gpt-4o
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "argo:gpt-4o"

  # ## Argo gpt-o1-preview
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "argo:gpt-o1-preview"

  model_kwargs:
    stream: true
    temperature: 0.4
    top_p: 0.2

master-code-llm:
  # Argo gpt-o1-preview
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "argo:gpt-o1-preview"

  model_kwargs:
    stream: true

visual_feedback:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  model_name: "gpt-4o-mini" # gpt-4o

  model_kwargs:
    stream: true

feedback_judge:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  model_name: "gpt-4o-mini"

  model_kwargs:
    stream: true

describe-vlm:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  # model_name: "Qwen/Qwen2-VL-72B-Instruct"
  model_name: "gpt-4o-mini"
  # model_kwargs: # Optional additional model parameters

  # ## SiliconFlow
  # api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
  # api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
  # model_name: "Qwen/Qwen2-VL-72B-Instruct"

  model_kwargs:
    stream: true
