name: codecad
channels:
  - conda-forge
dependencies:
  - pip=24.0
  - python>=3.11.0
  - pip:
      - cascadio==0.0.14
      - gmsh==4.13.1
      - plyfile==1.1
      - trimesh==4.5.1
      - pyglet<2
      - pyrender==0.1.45
      - openai==1.54.3
      - build123d==0.8.0
      - flake8==7.1.1
      - psycopg2-binary==2.9.10
      - sqlalchemy==2.0.36
      - pgvector==0.3.6
      - sqlite-vec==0.1.6
