code-llm:
  max_coding_iterations: 5

  ## Qwen/Qwen2.5
  api_key: "YOUR_API_KEY"
  api_base_url: "YOUR_API_BASE_URL" # Optional custom API base URL
  # model_name: "qwen-max" # or "qwen-max-latest"
  model_name: "gpt-4o"

  model_kwargs:
    stream: true
    temperature: 0.4
    top_p: 0.2

master-code-llm:
  api_key: "YOUR_API_KEY"
  api_base_url: "YOUR_API_BASE_URL" # Optional custom API base URL
  # model_name: "deepseek-r1"
  model_name: "gpt-4o"

  model_kwargs:
    stream: false
