visual_qa:
  ## OpenAI
  api_key: "YOUR_API_KEY"
  api_base_url: "YOUR_API_BASE_URL"
  model_name: "qwen-vl-plus"
  # model_name: "gpt-4o"

  model_kwargs:
    stream: true

visual_feedback:
  ## OpenAI
  api_key: "YOUR_API_KEY"
  api_base_url: "YOUR_API_BASE_URL"
  model_name: "qwen-vl-plus"
  # model_name: "gpt-4o"

  model_kwargs:
    stream: true

feedback_judge:
  api_key: "YOUR_API_KEY"
  api_base_url: "YOUR_API_BASE_URL"
  # model_name: "gpt-4o-mini"
  # model_name: "deepseek-v3"
  model_name: 'gpt-4o'

  model_kwargs:
    stream: true
