visualquality-vlm:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  model_name: "gpt-4o-mini"

  # ## SiliconFlow
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "Pro/Qwen/Qwen2-VL-7B-Instruct"
