code-llm:
  # SiliconFlow
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "deepseek-ai/DeepSeek-V2.5"

  # ## OpenAI
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1"
  # model_name: "gpt-4o"

  # ## Argo gpto1preview
  # api_key: "#NbhBUFZwTQaRNd!y$gpgARDtJ3Fd&T$btv@kee6eky#x2!^zm5Kd9rFirswBDk3MY9x%VMWtnlTpBpq3CBxL&"
  # api_base_url: "http://localhost:5000/v1" # Optional custom API base URL
  # model_name: "gpto1preview"

  model_kwargs:
    temperature: 0.2
    top_p: 0.1
