code-llm:
  max_coding_iterations: 5
  # ## 01.ai
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  # model_name: "yi-lightning"

  # # deepseek
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  # model_name: "deepseek-chat"

  ## Qwen/Qwen2.5
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  model_name: "qwen-max-latest" # or "qwen-max-latest"

  # ## OpenAI
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "http://localhost:33000/v1"
  # model_name: "gpt-4o"

  # ## Argo gpt-4o
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  # model_name: "argo:gpt-4o"

  # ## Argo gpt-o1-preview
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  # model_name: "argo:gpt-o1-preview"

  model_kwargs:
    stream: true
    temperature: 0.4
    top_p: 0.2

master-code-llm:
  ## Argo gpt-o1-preview
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "http://localhost:33000/v1" # Optional custom API base URL
  model_name: "argo:gpt-o1-preview"

  model_kwargs:
    stream: false
