embed:
  ## Siliconflow
  api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
  api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
  model_name: "Pro/BAAI/bge-m3" # "Pro/BAAI/bge-m3" for higher token/s

rerank:
  ## Siliconflow
  api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
  api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
  model_name: "Pro/BAAI/bge-reranker-v2-m3" # "Pro/BAAI/bge-reranker-v2-m3" for higher token/s

pgvector_store:
  connection_string: "postgresql://ppp:codecad_1s_g00d@localhost/codecad_db"
  collection_name: "test_collection"

sqlitevec_store:
  db_file: "test_vec.db"
  table: "test_table"
