describe-vlm:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  model_name: "gpt-4o"
  # model_kwargs: # Optional additional model parameters

  # ## SiliconFlow
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "Qwen/Qwen2-VL-72B-Instruct"

assist-llm:
  # ## OpenAI
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1"
  # model_name: "gpt-4o-mini"

  # ## 01.AI
  # api_key: "sk-dowBZNfa1fL6E6hsEb7cEaEe19514038B1Ed873903412f71"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "yi-lightning"

  ## Argo gpt-4o
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "argo:gpt-4o"

  # ## Argo gpt-o1-preview
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "argo:gpt-o1-preview"

vqa-vlm:
  ## OpenAI
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1"
  model_name: "gpt-4o-mini"

  # ## SiliconFlow
  # api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  # api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  # model_name: "Pro/Qwen/Qwen2-VL-7B-Instruct"

embed:
  ## Siliconflow
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "BAAI/bge-m3" # "Pro/BAAI/bge-m3" for higher token/s

rerank:
  ## Siliconflow
  api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
  api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
  model_name: "BAAI/bge-reranker-v2-m3" # "Pro/BAAI/bge-reranker-v2-m3" for higher token/s
