# ## 01.ai
# api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# model_name: "yi-lightning"

# # deepseek v3
api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_key: "sk-ad807e799c214306b2a03c1c2e1d3017"
api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# api_base_url: "https://api.deepseek.com/v1" # Optional custom API base URL
# model_name: "argo:gpt-4o"
model_name: "deepseek-v3"
# model_name: "deepseek-chat"

# # deepseek v2.5
# api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# model_name: "deepseek-v2.5"

# ## Qwen/Qwen2.5
# api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# model_name: "Qwen/Qwen2.5-72B-Instruct-128K"

## Argo gpt-4o
# api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# model_name: "argo:gpt-4o"

# ## Argo gpt-o1-preview
# api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# model_name: "argo:gpt-o1-preview"

model_kwargs:
  stream: true
  # temperature: 0.4
  # top_p: 0.2

# cheat_sheet_file: "../coding/cheat_sheet.md"
cheat_sheet_file: "../coding/cheat_sheet_full.md"
