## OpenAI
api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
# api_key: "sk-ad807e799c214306b2a03c1c2e1d3017"
api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
# api_base_url: "https://api.deepseek.com/v1" # Optional custom API base URL
# model_name: "argo:gpt-o1-preview"
model_name: "deepseek-r1"
# model_name: "deepseek-reasoner"

model_kwargs:
  stream: true
