build123d_retriever:
  db_file: "test_vec.db"
  table: "test_table"
  embedding_config:
    ## Siliconflow
    api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
    api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
    model_name: "Pro/BAAI/bge-m3" # "Pro/BAAI/bge-m3" for higher token/s
  rerank_config:
    ## Siliconflow
    api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
    api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
    model_name: "Pro/BAAI/bge-reranker-v2-m3" # "Pro/BAAI/bge-m3" for higher token/s

build123d_retriever_v2:
  cheat_sheet_file: "../../coding/cheat_sheet.md"
  llm_filter:
    # deepseek v3
    api_key: "sk-EFhZxTqkXfedmKP_p9uUwDWJqIMvY0LGSClJ56RpZM7yO4Byvwb7vuRHpXc"
    api_base_url: "https://oneapi.service.oaklight.cn/v1" # Optional custom API base URL
    model_name: "deepseek-v3"

    model_kwargs:
      stream: true
      temperature: 0.4
      top_p: 0.2
