build123d_retriever:
  db_file: "test_vec.db"
  table: "test_table"
  embedding_config:
    ## Siliconflow
    api_key: "sk-gpictjyjiywniufdjmdudqbidrqprcblsykmmvizeahoqbyr"
    api_base_url: "https://api.siliconflow.com/v1" # Optional custom API base URL
    model_name: "Pro/BAAI/bge-m3" # "Pro/BAAI/bge-m3" for higher token/s
